Intervention additions
zenna/OmegaCore.jl pull request #16
Opened 2020-07-01 19:38 UTC by riadas

2020-07-01 20:06 UTC, zenna commented
Please add a test that uses more than  2 interventions and also passes inference tests - see `isinferred`

2020-07-01 20:07 UTC, zenna commented
Also if it fails isinferred let me know and we can track down why together

2020-07-07 01:21 UTC, zenna commented on src/interventions/intervene.jl
> +"mergeinterventions"
I think you'll loose type information if you use a vector `[]`.  Use a tuple

2020-07-07 01:22 UTC, zenna commented on src/util/namedtuple.jl
> +    if K1 ∩ K2 == [:intervene]
There shouldn't be any intervene in mergef, This is what the first argument `f` of `mergef` is for

2020-07-07 01:32 UTC, zenna commented on src/space/abstractomega.jl
>  tag(ω::AbstractΩ, tags) =
Instead of these two versions of tag you could do use a default argument`tag(ω::AbstractΩ, tags, mergefunc = mergetag) = ...`

2020-07-07 04:29 UTC, riadas commented on src/interventions/intervene.jl
> +Intervention(x::Tuple) = Intervention(x[1], x[2])
@zenna I wanted to use the commented lines, but they didn't seem to work so I had to switch to the tuple-centric method instead... Also not sure if this should support constants other than `<:Number` values...

2020-07-07 04:57 UTC, zenna commented on src/interventions/intervene.jl
> +Intervention(x::Tuple) = Intervention(x[1], x[2])
In what sense did they not work.

You shouldn't need to check the types at runtime like you did

`Intervention(x::Pair{X, <:Number} ...`

2020-07-07 04:58 UTC, zenna commented on src/interventions/intervene.jl
> +Intervention(x::Tuple) = Intervention(x[1], x[2])
Number is fine for now, can generalize later

2020-07-07 05:02 UTC, zenna commented on src/interventions/intervene.jl
> +  else
This seems like it would break type inference.  Can the compiler figure out the return type given the input type? Note that the type of a NamedTuple contains the type of the values and the symbol names.  For the compiler to figure out the return type it would have to figure out the value of `ks`, and the types of `values`.  This would be hard since you put these values in an `Any` Array.

2020-07-07 05:09 UTC, zenna commented on src/interventions/intervene.jl
> +  else
This is why fuctions on named tuples are often generated functions

2020-07-07 07:02 UTC, riadas commented on src/interventions/intervene.jl
> +Intervention(x::Tuple) = Intervention(x[1], x[2])
Using `Variable` in line 14 caused the break, making it general solved the problem.

2020-07-07 07:03 UTC, riadas commented on src/interventions/intervene.jl
> +  else
I think that the new function (newest commit) hopefully resolves this?
```
function mergetags(nt1::NamedTuple{K1, V1}, nt2::NamedTuple{K2, V2}) where {K1, K2, V1, V2}
  if K1 ∩ K2 == [:intervene]    
    merge(merge(nt1, nt2), (intervene = mergeinterventions(nt2[:intervene], nt1[:intervene]),))
  else
    Core.println(K1, " naa ", K2)
    @assert false "Unimplemented"
  end
end
```

2020-07-07 14:13 UTC, zenna commented on src/interventions/intervene.jl
> +  else
write a test for merge tags

2020-07-09 14:12 UTC, zenna commented on test/intervene.jl
> +using ..Interventions
This file is not within a module so it doesn't make sense to do `..Interventions`

You should do using `OmegaCore.Interventions`

2020-07-09 14:15 UTC, zenna commented on test/intervene.jl
> +  @test string(mergetags(nt1, nt2)) == string((intervene = yiii.i,))
Why are you converting to a `string`?

2020-07-09 14:22 UTC, zenna commented on test/intervene.jl
> +  nt1 = (intervene = yi.i,)
In the tag `(intervene = x,)` `x` should be of type `Intervened` (i.e., an Intervened Random Variable) not `Intervention`

2020-07-09 14:30 UTC, zenna commented on test/intervene.jl
> +  nt1 = (intervene = yi.i,)
Actually ignore htis

2020-07-09 14:52 UTC, zenna commented on test/intervene.jl
> +  @test string(mergetags(nt1, nt2)) == string((intervene = yiii.i,))
There are almost no situations where you need to convert something to a string for equality  trest.  I imagine you are testing with `string` because your normal equality test is failing.  The question is why.

There are two reasons:

The first reason is that `(ω -> 100) == (ω -> 100)` is `false`.  This is perhaps surprising, but in general testing for the equality of two programs is undecidable, so you should check to see what julia is actually doing (use `@which` or the debugger)

Even when you fix that your test will fail.  See below.

Type inference does pass though, so that is good

```
function test_mergetags()
  x = 1 ~ Normal(0.0, 1.0)
  y(ω) = x(ω) + 10.0
  c1 = (ω -> 100.0)
  c2 = (ω -> 200.0)
  yi = intervene(y, x => c1)
  yii = intervene(yi, x => c2)
  yiii = intervene(yi, (x => c1, x => c2))
  yiii2 = intervene(yi, (x => c2, x => c1))

  nt1 = (intervene = yi.i,)
  nt2 = (intervene = yii.i,)
  ntmerged = mergetags(nt1, nt2)
  @test isinferred(mergetags, nt1, nt2)

  # Only one of these should be true
  @test ntmerged.intervene == yiii.i
  @test ntmerged.intervene == yiii2.i
end
```

2020-07-12 02:48 UTC, zenna requested changes
Made changes, also there are some changes in master causing conflict.  Merge from the latest master and fix conflicts

2020-07-12 02:48 UTC, zenna commented on src/interventions/intervenepass.jl
> +  # if (index <= length(i.is))
Remove these comments

2020-07-12 02:48 UTC, zenna commented on src/space/abstractomega.jl
> +  # @assert false
Remove these comments

2020-07-12 02:48 UTC, zenna commented on test/intervene.jl
> +  c2 = (ω -> 200.0)
Add a test where the intervention changes the return type and check that the return type is the Union

2020-07-12 02:48 UTC, zenna commented on src/interventions/intervenepass.jl
> +
You need to add a case for more than 5 (for which we're allowing type inference to fail)

2020-07-12 02:48 UTC, zenna commented on src/interventions/intervene.jl
> +    Core.println(K1, " naa ", K2)
Remove this

2020-07-13 02:58 UTC, riadas commented on src/interventions/intervene.jl
> +    Core.println(K1, " naa ", K2)
Remove all four lines?

2020-07-13 03:23 UTC, zenna commented on src/interventions/intervene.jl
> +    Core.println(K1, " naa ", K2)
Just the print, what is "naa".  Maybe I put that there?!

2020-07-13 03:44 UTC, riadas commented on src/interventions/intervene.jl
> +    Core.println(K1, " naa ", K2)
Oh haha yeah you did

2020-07-13 03:48 UTC, riadas commented on test/intervene.jl
> +  c2 = (ω -> 200.0)
Not sure if I fully understand this, but the test I just added called `test_changed_rettype_merge` is failing `isinferred`...

2020-07-13 05:04 UTC, zenna commented on test/intervene.jl
> +  c2 = (ω -> 200.0)
Don't use `isinferred` -- that will fail (see if you can figure out why).

You'll need something like:

`@test Base.returntype(f, omega) == Union{...}`

2020-07-13 05:34 UTC, riadas commented on test/intervene.jl
> +  c2 = (ω -> 200.0)
Cool fixed

2020-07-13 15:12 UTC, zenna approved these changes
Looks good!

2020-07-13 15:13 UTC, merged